services:
  - type: web
    name: tg-bet-alert
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_PIN
        value: "2565"
